### ISSUE TITLE
Play OutOfMemoryError

### ISSUE THREAD

**Issue by dr0i** [hbz/nwbib#108]
2015-05-29 13:25:31,933 - [ERROR] - from akka.actor.ActorSystemImpl in play-akka.actor.default-dispatcher-146554 
Uncaught error from thread [play-akka.actor.default-dispatcher-146577] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3326) ~[na:1.8.0_05]
        at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137) ~[na:1.8.0_05]
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121) ~[na:1.8.0_05]
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421) ~[na:1.8.0_05]
        at java.lang.StringBuilder.append(StringBuilder.java:136) ~[na:1.8.0_05]
        at java.lang.StringBuilder.append(StringBuilder.java:76) ~[na:1.8.0_05]
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:457) ~[na:1.8.0_05]
        at java.lang.StringBuilder.append(StringBuilder.java:166) ~[na:1.8.0_05]
        at java.util.StringJoiner.add(StringJoiner.java:185) ~[na:1.8.0_05]
        at java.lang.String.join(String.java:2491) ~[na:1.8.0_05]
        at controllers.nwbib.Application.lambda$facets$14(Application.java:449) ~[nwbib.nwbib-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
        at controllers.nwbib.Application$$Lambda$27/1813160935.apply(Unknown Source) ~[na:na]
        at play.core.j.FPromiseHelper$$anonfun$map$1.apply(FPromiseHelper.scala:98) ~[com.typesafe.play.play_2.11-2.3.4.jar:2.3.4]
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:236) ~[org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.util.Try$.apply(Try.scala:191) ~[org.scala-lang.scala-library-2.11.2.jar:na]

**Comment by dr0i** [comment]
See also hbz/lobid#107

**Comment by dr0i** [comment]
See also my comment at https://github.com/hbz/lobid/issues/107#issuecomment-112816550.

**Comment by dr0i** [comment]
Doubled assignation of RAM via `/etc/monit/conf.d/play-instances.rc` . Stable for more than month now, closing.
